common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "sst_2"
  data_file_path: ~/fednlp_data/data_files/sst_2_data.h5
  partition_file_path: ~/fednlp_data/partition_files/sst_2_partition.h5
  partition_method: "niid_label_clients=20_alpha=1"
  reprocess_input_data: false

model_args:
  model_type: "mor_llama"
  model_class: "transformer"
  model: "HuggingFaceTB/SmolLM-135M"
  do_lower_case: false
  formulation: "classification"

mor_args:
  mor_enable: true
  mor_type: "expert"
  mor_skip_router_first_round: false
  mor_adaptive_router_weight: true
  mor_router_weight_mode: "absolute"
  mor_router_weight_tau: 1.0
  mor_router_weight_tau_warmup: true
  mor_router_weight_tau_warmup_start: 2.0
  mor_router_weight_tau_warmup_end: 0.7
  mor_router_weight_tau_warmup_rounds: 200
  mor_capacity: "1.0,0.8,0.6"
  mor_rand_router: false
  mor_router_type: "linear"
  mor_z_loss: false
  mor_z_coeff: 0
  mor_temp: 1.0
  mor_loss_coeff: 0.0001
  mor_expert_cap_warmup_step: 0
  mor_expert_router_func: "sigmoid"
  mor_expert_alpha: 0.1
  mor_expert_sampling: "aux_loss"
  mor_expert_include_first: true
  mor_expert_coeff: 0.0001
  mor_expert_gating: "weighted"
  mor_token_router_func: "sigmoid"
  mor_token_alpha: 0.1
  mor_token_balancing: "loss"
  mor_token_coeff: 0
  mor_token_u: 0.001
  mor_token_gating: "weighted"
  mor_token_bal_warmup_step: 0

recursive_args:
  recursive_enable: true
  recursive_base_depth: null
  recursive_num_recursion: 3
  recursive_sharing: "middle_cycle"
  recursive_ln_share: false
  recursive_initialization: "average"

kv_sharing_args:
  kv_sharing_enable: false
  kv_sharing_base_depth: null
  kv_sharing_num_recursion: null
  kv_sharing_sharing: null

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 20
  client_num_per_round: 8
  comm_round: 200
  epochs: 2
  batch_size: 20
  eval_batch_size: 8
  max_seq_length: 64
  fp16: true
  output_dir: "./outputs/compare_mor_expert_adaptive_warmup_24g"
  client_optimizer: AdamW
  server_optimizer: sgd
  server_momentum: 0.9
  server_lr: 1
  learning_rate: 0.00005
  weight_decay: 0.001
  gradient_accumulation_steps: 1
  clip_grad_norm: true
  fedprox_mu: 0
  evaluate_during_training: false
  evaluate_during_training_steps: 10
  freeze_layers: ''
  is_debug_mode: false
  momentum: 0.9
  max_grad_norm: 1
  ci: 0

validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 1
  using_gpu: true
  gpu_mapping_file: config/simulation/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "sp"
  is_mobile: 0

tracking_args:
  enable_wandb: false
  wandb_entity: fedml-team
  wandb_only_server: true
  wandb_key: 404bae40078b1624faed523c4e9d25b40590e537
  wandb_project: fednlp_compare_24g
  wandb_name: compare_mor_expert_adaptive_warmup_24g
